use_frameworks!

target 'GreetingLib_Example' do
  pod 'GreetingLib', :path => '../'

  target 'GreetingLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
